try{
 console.log("Try Me")
 console.log(x)
}
catch(e){
    //retry logic
    //fallback mechanism
    //logging
    //custom error
    console.log(e)
}
finally{
    console.log("Im gonna run")
}